### ISSUE TITLE
Design Docs Review #1

### ISSUE THREAD

**Issue by volynsal** [volynsal/Robbinhood#1]
Good job so far, just a few things to change:

MVP LIST
- [x] Make hosting on heroku your first MVP, and your production readme 7th. 
- [x] Let's switch the order of dashboard/portfolio and stock details. It will be much easier to get your dashboard online if you already have all of your stock data figured out. 
- [x] You're going to need to build out your transactions functionality when you build out your dashboard/portfolio, so make sure to include this in your MVP list's details. 

SCHEMA
- [x] We definitely do not want to be storing our users social security numbers in our database like this, especially not as plain integers. Your app isn't going to use real money transactions, and we should remove the ssn's and the bank accounts entirely. Instead, a user can just have another column of their current funds (probably initialize this at a number you'd be able to use).
- [x] Instead of "stock_pages", just call them "stocks"
- [x] What is the relationship between portfolios and users? Does a user have many portfolios? If they only have one, you'll also need a joins table between stocks and portfolios to represent the different stocks a user owns. 
- [x] You'll also probably want a transactions table to keep a record of a users stocks over time.

SAMPLE STATE
- [x] If we were storing ssn's, sending them up to the front end would be one of the most dangerous things we could do, and the same for bank accounts. Remove both of these. 
- [ ] A user should have more data, like their portfolioId or an array of ownedStockIds. Think about what you'll want to reference about a user while displaying information for that user. 
- [ ] All of the stock data that you grab from the api and that you'll want to reference for your app should be in the frontend state. 
- [ ] Rearrange your portfolio slice of state after rearranging their relationship in you schema, same with transactions. Make sure to include all the details you'll want to be able to reference from the frontend.

**Comment by jliversi** [comment]
SCHEMA
- [ ] Add a portfolios table and a joins table for portfolios/securities. 
- [ ] Remove the market_value from users table, this will be calculated in real time on the front end.
- [ ] Remove trigger from orders table. We'll just use positive/negative integers in the size column. 

SAMPLE STATE
- [ ] Make any changes necessary to reflect your changes to schema (ex. remove trigger from orders)
- [ ] Add a key to your users with an array of their watched stocksIds. We can also remove watchlist_items from the sample state.
- [ ] Fill out your stocks slice with all of the information that we'll need to reference on the front end (the information we'll be grabbing from our external api) 
- [ ] Add a portfolio slice of state with all of the necessary data

BACKEND ROUTES 
- [ ] No need for a stocks show route. We'll only ever grab multiple stocks at a time.
- [ ] As watchlist data will come up through the users route, we probably don't need a "get" route for watchlists. 

FRONTEND ROUTES
- [ ] Great job overall, just flesh out a couple of components (a news component should have nested newsItem components) and make sure indentation is clear to indicate the nesting. 
- [ ] Instead of having a separate route for the orders, this will just be a component on any given stock page, like on real robinhood. Make the updates to reflect this.

**Comment by volynsal** [comment]
Follow-up comments:

For SAMPLE STATE:
-Please double-check to see if my portfolio slice looks right to you.

For FRONTEND ROUTES:
-The '/orders/' route will allow the user to view a full transaction/order log. The show page will show more details for one particular order. Should I still trash both?

**Comment by jliversi** [comment]
Hey Alex, most of the changes look really good. To address your two comments:
For the portfolios slice, we'll need reference not only to the stocks our currentUser owns, but also the number of stocks they own. One way to do this would be to have a key in portfolio slice of stocks, which then points to another object which has keys of stockIds (or ticker strings) and values of the number of each that the user owns.

For `/orders`, I hadn't realized robinhood had this but I now see it in profile/history. You can definitely include this route in your docs, though you probably won't implement it until a fair bit down the line.
